version: "3"
services:
  devgateway:
    image: dev_gateway_img
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - '5680'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - gatewaydata:/usr/src/data
    networks:
      dev_api_layer:
        aliases:
          - gatewaypush
      dev_db_layer:
      dev_gateway_layer:
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5680/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
  nginx: 
    image: nginx:latest
    container_name: nginx_dev_cont
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - '5678:5678'
    networks:
      dev_app_layer:
      dev_gateway_layer:
    depends_on:
      - devgateway
  devworker:
    image: dev_worker_img
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    ports:
      - '5679'
    expose:
      - '8765'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - workerdata:/usr/src/data
    networks:
        dev_api_layer:
        dev_db_layer:
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5679/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - devgateway
networks:
  dev_api_layer: 
    driver: bridge
  dev_app_layer:
    driver: bridge
  dev_db_layer:
    driver: bridge
  dev_gateway_layer:
    driver: bridge
volumes:
  allocatordata:
  gatewaydata:
  workerdata:
  devdbsingledata: